In [1]:
import numpy as np
np.random.seed(42)

In [3]:
means = [[2,2], [4,2]]
cov = [[.3, .2], [.2, .3]]
N = 10
X0 = np.random.multivariate_normal(means[0], cov, N).T # (2, N)
X1 = np.random.multivariate_normal(means[1], cov, N).T # (2, N)
X = np.concatenate((X0, X1), axis = 1) # (2, 2N)
y = np.concatenate((np.ones((1, N)), -1 * np.ones((1, N))), axis = 1)
#Xbar
X = np.concatenate((np.ones((1, 2*N)), X), axis=0) # (3, 2N)

In [6]:
X, y

(array([[1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.5924476 , 2.12515297, 2.90022305, 1.99393967, 2.22241862,
         1.92406503, 2.20168602, 1.27625967, 2.48875075, 1.61622976,
         4.28110173, 4.82064742, 3.2904726 , 3.81160828, 3.96343515,
         3.47538677, 3.66804806, 5.12608956, 4.02333654, 4.39855353],
        [1.66908582, 1.99049531, 2.57829894, 2.4666991 , 1.43396309,
         1.751851  , 2.47523598, 1.6927408 , 2.35046677, 2.05250681,
         2.19807251, 2.28568755, 1.89700158, 2.26040184, 1.67492882,
         2.16321763, 2.36777798, 3.49365554, 1.88961639, 1.50968569]]),
 array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1., -1.]]))

In [7]:
def h(w, X):
  return np.sign(np.dot(w.T, X)) # (1, d) x (d, 2N) => (1,2N)

def has_coverged(X, y, w):
  return np.array_equal(h(w, X), y)

def perceptron(X, y, w_init):
  w = [w_init]
  N = X.shape[1]
  d = X.shape[0]
  mis_points = []
  while True:
    # shuffle data, ví dụ array([1, 7, 4, 2, 8, 6, 5, 0, 9, 3])
    mix_id = np.random.permutation(N)
    for i in range(N):
      xi = X[:, mix_id[i]].reshape(d, 1)
      yi = y[0, mix_id[i]]
      # (1, d) x (d, 1) => (1,1)
      if h(w[-1], xi)[0] != yi:
        mis_points.append(mix_id[i])
        w_new = w[-1] + yi * xi
        w.append(w_new)
    # lặp cho đến khi không còn điểm nào bị misclassified
    if has_coverged(X, y, w[-1]):
      break
  return (w, mis_points)

In [8]:
d = X.shape[0]
w_init = np.random.randn(d, 1)
(w, m) = perceptron(X, y, w_init)

In [9]:
np.random.permutation(N)

array([1, 7, 4, 2, 8, 6, 5, 0, 9, 3])